### ISSUE TITLE
Adding the ability to draw more primitive shapes

### ISSUE THREAD

**Issue by tupini07** [BenMakesGames/PlayPlayMini#3]
I think PlayPlayMini should have more options for drawing shapes. Right now, it only has `DrawRectangle` and `DrawFilledRectangle` in the `GraphicsManager` service. But sometimes, I want to draw circles, triangles, and lines too. It would be nice if there were `Draw{X}` and `DrawFilled{X}` methods for these shapes as well. In my games I have been using the shape drawing logic from [Monogame.Extended.ShapeExtensions](https://github.com/craftworkgames/MonoGame.Extended/blob/20fb26d6c1f75d65e8c05f2f7070e383c4579a69/src/cs/MonoGame.Extended/Math/ShapeExtensions.cs#L250) to extend the GraphicsManager and draw my own shapes, but it would be great if PlayPlayMini had this feature built-in!

What do you think? I could try adding these operations if you want. I think leveraging the `MonoGame.Extended` library is probably best for maintainability, but on the other hand it brings a lot of (unnecessary) baggage with it, so maybe just copying over the drawing code for the shapes would be best?

**Comment by BenMakesGames** [comment]
I do provide a couple (non-obvious) ways to draw circles and lines... I haven't made them more-obvious, because they perform very badly! (especially the filled circle!)

if you've got frames to spare:

```
// draw a filled circle centered at (50, 50), with radius 10 (in red)
GraphicsManager.DrawPoints(Generators.Circle(50, 50, 10), Color.Red);
```

if you're drawing the same circle all the time, it'd be better to `.ToList()` the output of `Generators.Circle` and keep it around, but if you're drawing the same circle all the time, it'd be even BETTER to just pre-render a picture/sprite... so `Generators.Circle` (and the other `Generator` methods) really are just bad...

I agree with your pros and cons about adding a dependency on `MonoGame.Extended`. I'll think on that.

but without testing their code, my intuition is that it'll definitely perform better than mine... though I also feel like there's gotta' be an even-better way. my understanding is that it's best to try and minimize draw calls. there's probably other factors, though; maybe their code is RAD. still, I'd be curious to performance-test various approaches. some ideas that come to mind, especially for filled shapes:
* draw the circle line-by-line (top to bottom, or left to right; whichever covers less distance)
* find some algorithm for breaking a circle down into a minimum number of rectangles, and draw each of those
* use 3D to render a circle made of triangles onto a texture, and draw that??

this problem intrigues me, and it's a long-standing issue with PlayPlayMini... I may look into it this afternoon. I'll get back to you with what I find, when I find something.

**Comment by BenMakesGames** [comment]
I found this algorithm online for drawing ellipses that fit rectangles: https://stackoverflow.com/a/54488533 I can provide an overload for drawing circles the way people typically expect (specifying a center and radius).

curiously, when applying the algorithm directly to PlayPlayMini, filled ellipses perform better than outlines! but both are an order of magnitude faster than PlayPlayMini's `Generators`. here's some demos:

using `Generators`:
![image](https://github.com/BenMakesGames/PlayPlayMini/assets/1587505/36a26cd6-d3ef-4b6c-aaa6-770cedfca62b)

using "DrSheldon"'s algorithm (faster, and note that the top, bottom, left, & right edges look nicer, too!)
![image](https://github.com/BenMakesGames/PlayPlayMini/assets/1587505/e5d34b0e-a771-492e-9ad0-aa4e0670b40f)

here's some ellipses:
![image](https://github.com/BenMakesGames/PlayPlayMini/assets/1587505/ea478edc-5030-483a-bc85-a2f2d83733cf)

here's the outlines for those same ellipses:
![image](https://github.com/BenMakesGames/PlayPlayMini/assets/1587505/240c99a0-c409-4039-989b-1ece1544763b)

I'm going to play around a little more with these (for example, see if it helps more than it hurts to do extra logic to check if we've gone out of bounds of the screen), but hope to have this released this evening.

I realize this is only circles/ellipses, and that there are many other interesting polygons to draw (or even just slanted lines!) I'll get to other shapes another time!

**Comment by tupini07** [comment]
ha that's a great investigation! good find on the ellipse drawing algorithm :) 

> I'm going to play around a little more with these (for example, see if it helps more than it hurts to do extra logic to check if we've gone out of bounds of the screen), but hope to have this released this evening.

thanks a lot :) 

> I realize this is only circles/ellipses, and that there are many other interesting polygons to draw (or even just slanted lines!) I'll get to other shapes another time!

yeah 😅 I understand. I think rectangles and circles covers the majority of the use cases. Maybe lines would be next? But I imagine that's easier to add and can already be done with the DrawRectangle methods.

**Comment by tupini07** [comment]
ha that's a great investigation! good find on the ellipse drawing algorithm :) 

> I'm going to play around a little more with these (for example, see if it helps more than it hurts to do extra logic to check if we've gone out of bounds of the screen), but hope to have this released this evening.

thanks a lot :) 

> I realize this is only circles/ellipses, and that there are many other interesting polygons to draw (or even just slanted lines!) I'll get to other shapes another time!

yeah 😅 I understand. I think rectangles and circles covers the majority of the use cases. Maybe lines would be next? But I imagine that's easier to add and can already be done with the DrawRectangle methods.

**Comment by BenMakesGames** [comment]
I have released a new version of `PlayPlayMini.GraphicsExtensions` which has the ellipses (seen above) and line-drawing methods!

(I also released a new version of `PlayPlayMini` itself, which marks the `Generator` methods `[Obsolete]`!)

I'm gonna close this ticket. other polygons can come later. you mentioned triangles... feel free to open another ticket (or PR) for that.

P.S. if you've got a game to show off made with PlayPlayMini, I'd love to see!

P.P.S. just to set expectations: I start a new job Oct 30th, and am not working this week, so am uncommonly free this week! I won't always be able to investigate and implement new features as quickly as this one :P you caught me at a real good time!

**Comment by BenMakesGames** [comment]
@tupini07 I actually found a good triangle algorithm online, and incorporated that, too :P (https://web.archive.org/web/20050408192410/http://sw-shader.sourceforge.net/rasterizer.html) just now pushed that to NuGet. it only does solid triangles, and I couldn't make heads or tails of the algorithm in order to try adapting it to do outlines only. a problem for another day, I suppose...

**Comment by tupini07** [comment]
cool ❤️!! That was really fast

> P.S. if you've got a game to show off made with PlayPlayMini, I'd love to see!

Just noticed how in my original post I said `... in my games ...` makes it sound like I have anything to show. But I don't 😅 they're just lots of small experiments. Though I'm lately getting more motivation to do and, more importantly, finish something. 

> P.P.S. just to set expectations: I start a new job Oct 30th...

ha I was lucky then! Best of luck in your new job :D
